# generated by datamodel-codegen:
#   filename:  workdir/k3s_m_crossplane_io_v1alpha1_cluster.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class ForProvider(BaseModel):
    clusterInit: bool | None = None
    """
    ClusterInit enables embedded etcd for HA multi-server setup.
    """
    datastoreEndpoint: str | None = None
    """
    DatastoreEndpoint is an external datastore URL for HA (MySQL/PostgreSQL).
    """
    disableServiceLB: bool | None = None
    """
    DisableServiceLB disables the default ServiceLB load balancer.
    """
    disableTraefik: bool | None = None
    """
    DisableTraefik disables the default Traefik ingress controller.
    """
    extraArgs: str | None = None
    """
    ExtraArgs are additional arguments passed to k3s server.
    """
    host: str
    """
    Host is the DNS name or IP address of the target machine.
    """
    k3sChannel: str | None = 'stable'
    """
    K3sChannel is the release channel (stable, latest, v1.28, etc.).
    """
    k3sVersion: str | None = None
    """
    K3sVersion is the specific k3s version to install (e.g., "v1.28.2+k3s1").
    """
    port: int | None = 22
    """
    Port is the SSH port. Defaults to 22.
    """
    tlsSAN: str | None = None
    """
    TLSSAN adds an additional hostname or IP as a TLS Subject Alternative Name.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    """
    ClusterParameters are the configurable fields of a Cluster.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    k3sVersion: str | None = None
    """
    K3sVersion is the installed version reported by the server.
    """
    ready: bool | None = None
    """
    Ready indicates the k3s server is running.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    """
    ClusterObservation are the observable fields of a Cluster.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Cluster(BaseModel):
    apiVersion: Literal['k3s.m.crossplane.io/v1alpha1'] | None = (
        'k3s.m.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Cluster'] | None = 'Cluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    A ClusterSpec defines the desired state of a Cluster.
    """
    status: Status | None = None
    """
    A ClusterStatus represents the observed state of a Cluster.
    """


class ClusterList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Cluster]
    """
    List of clusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """