# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_modeldeployment.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, conint, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class ClusterSelector(BaseModel):
    matchLabels: dict[str, str] | None = None


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class ModelCacheRef(BaseModel):
    name: constr(min_length=1)
    """
    ModelCache resource name in the same namespace.
    """


class Selector(BaseModel):
    cel: constr(min_length=1, max_length=10240) | None = None
    """
    A DRA CEL expression evaluated against one device. Reads device.driver, device.attributes["<driver>"].<name> (typed), and device.capacity["<driver>"].<name> (a Quantity), with quantity() and semver() helpers, e.g. device.capacity["gpu.nvidia.com"].memory.compareTo(quantity("141Gi")) >= 0.
    """


class Device(BaseModel):
    count: conint(ge=1, le=64) | None = 1
    """
    How many matching devices a node must have. For a GPU request this is the per-node GPU count.
    """
    name: constr(min_length=1, max_length=63)
    """
    Name of this request. Mirrors a DRA DeviceRequest name; carried through to the ResourceClaim.
    """
    selectors: list[Selector] = Field(..., max_length=8, min_length=1)
    """
    Selectors a device must satisfy, all ANDed. Each is a one-of; today only cel is supported.
    """


class NodeSelector(BaseModel):
    devices: list[Device] = Field(..., max_length=16, min_length=1)
    """
    Device requests. A pool matches a request when it has a device whose count covers the request and whose driver, attributes, and capacity satisfy every selector.
    """


class Metadata(BaseModel):
    annotations: dict[str, str] | None = None
    labels: dict[str, str] | None = None


class ConfigMapKeyRef(BaseModel):
    key: str
    name: str
    optional: bool | None = None


class SecretKeyRef(BaseModel):
    key: str
    name: str
    optional: bool | None = None


class ValueFrom(BaseModel):
    configMapKeyRef: ConfigMapKeyRef | None = None
    secretKeyRef: SecretKeyRef | None = None


class EnvItem(BaseModel):
    name: str
    value: str | None = None
    valueFrom: ValueFrom | None = None


class Container(BaseModel):
    args: list[str] | None = None
    """
    Container args, passed through to the serving engine. Includes the model identifier (e.g. --model=...) and any parallelism flags.
    """
    command: list[str] | None = None
    """
    Container entrypoint override, passed through verbatim. For a Leader or Worker, the command owns cross-node coordination and addresses the leader through $(MODELPLANE_LEADER_ADDRESS), which Modelplane injects into every engine container.
    """
    env: list[EnvItem] | None = None
    """
    Environment variables. Supports valueFrom.secretKeyRef for secrets like HF_TOKEN.
    """
    image: constr(min_length=1)
    """
    Container image.
    """
    name: constr(min_length=1)
    """
    Container name. The container named "engine" is the inference engine.
    """


class ImagePullSecret(BaseModel):
    name: str


class Spec(BaseModel):
    containers: list[Container] = Field(..., max_length=1, min_length=1)
    """
    Containers for the engine pod. v0.1 supports a single container, which must be named "engine" (the inference engine). Sidecar / multi-container support is tracked separately.
    """
    imagePullSecrets: list[ImagePullSecret] | None = None
    """
    Image pull secrets for private registries (NGC etc.).
    """


class Template(BaseModel):
    metadata: Metadata | None = None
    """
    Metadata applied to the member's pods. Useful for labels and annotations that control cluster-level features like service mesh injection.
    """
    spec: Spec | None = None
    """
    Pod spec for this member's engine pods.
    """


class Member(BaseModel):
    count: conint(ge=1, le=63) | None = None
    """
    Number of follower pods, for a Worker only. Each follower is one pod on one node, so this is also the number of follower nodes. Defaults to 1. No schema default - the apiserver applies defaults before CEL validation, so a default here would inject count onto Standalone and Leader members and trip the rule that forbids it.
    """
    nodeSelector: NodeSelector
    """
    The per-node device request for this member's engine pods: what devices each pod needs. The scheduler matches it against a candidate pool's InferenceClass devices (surfaced on InferenceCluster status.gpuPools) and places the group on a pool that satisfies every member. claim: DRA requests also become DeviceRequests in the ResourceClaim the serving pods bind GPUs through. At least one request must resolve to a claimable (claim: DRA) device; a member that matches only synthetic devices leaves its pods nothing to claim, so the scheduler treats such a pool as ineligible and the deployment reports InsufficientCapacity. A GPU request's count is the GPUs per node.
    """
    role: Literal['Standalone', 'Leader', 'Worker'] | None = 'Standalone'
    """
    The member's role in the group. Standalone is a lone pod; a Leader coordinates and serves while its Workers join it. Defaults to Standalone.
    """
    template: Template
    """
    Pod template for this member's engine pods. A curated subset of PodTemplateSpec.
    """


class Worker(BaseModel):
    members: list[Member] = Field(..., max_length=2, min_length=1)
    """
    The group's pods. Either a single Standalone member, or one Leader and one or more Workers.
    """
    name: constr(min_length=1, max_length=63)
    """
    Identifies the group within the deployment. Becomes part of the composed workload names, so it must be a DNS label.
    """
    replicas: conint(ge=1, le=64) | None = 1
    """
    How many identical copies of this group to run per ModelReplica. Maps to the composed Deployment's or LeaderWorkerSet's replica count. Defaults to 1.
    """


class SpecModel(BaseModel):
    clusterSelector: ClusterSelector | None = None
    """
    Optional label selector to filter InferenceClusters. If omitted, all ready clusters are candidates.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    modelCacheRef: ModelCacheRef | None = None
    """
    Reference to a ModelCache in the same namespace. Optional for single-node groups; required for any group that spans multiple nodes (a Leader with one or more Workers), since every pod in the gang mounts it.
    """
    replicas: conint(ge=1, le=10)
    """
    How many ModelReplicas to fan out to. Each replica is a complete serving instance scheduled to one InferenceCluster.
    """
    workers: list[Worker] = Field(..., max_length=8, min_length=1)
    """
    The shape of a ModelReplica's inference engines, as an array of worker groups. A group is one serving unit: a Standalone pod, or a gang of a Leader and one or more Workers coordinating across nodes. Modelplane composes the whole array once per ModelReplica; a group composes to a Deployment (Standalone) or a LeaderWorkerSet (Leader/Worker), but the workload kind is an implementation detail. Modelplane is unopinionated about the engine: parallelism, quantization, and KV transfer all live in the members' engine flags, written by the user, never injected by Modelplane.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Replicas(BaseModel):
    ready: int | None = None
    total: int | None = None


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    replicas: Replicas | None = None


class ModelDeployment(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['ModelDeployment'] | None = 'ModelDeployment'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: SpecModel
    status: Status | None = None


class ModelDeploymentList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[ModelDeployment]
    """
    List of modeldeployments. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """