# generated by datamodel-codegen:
#   filename:  workdir/vultr_m_crossplane_io_v1alpha1_blockstorage.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class SnapshotIDRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SnapshotIDSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    blockType: str | None = None
    """
    The subscription tier of the block storage volume.
    """
    bootable: bool | None = None
    """
    Whether or not this block device can be used as a bootable volume.
    """
    label: str | None = None
    """
    The user-supplied label.
    """
    region: str
    """
    The Region id where the Block Storage is located.
    """
    sizeGb: int
    """
    Size of the Block Storage in GB.
    """
    snapshotIDRef: SnapshotIDRef | None = None
    """
    A NamespacedReference to a named object.
    """
    snapshotIDSelector: SnapshotIDSelector | None = None
    """
    NamespacedSelector selects a namespaced object.
    """
    snapshotId: str | None = None
    """
    The snapshot_id from which this block device was cloned.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    """
    ForProvider holds the user-supplied parameters for this Blockstorage.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    attachedToInstance: str | None = None
    """
    The Instance id with this Block Storage attached.
    """
    attachedToInstanceIp: str | None = None
    """
    The attached instance IP.
    """
    attachedToInstanceLabel: str | None = None
    """
    The attached instance label.
    """
    blockType: str | None = None
    """
    The subscription tier of the block storage volume.
    """
    bootable: bool | None = None
    """
    Whether or not this block device can be used as a bootable volume.
    """
    cost: int | None = None
    """
    The monthly cost of this Block Storage.
    """
    dateCreated: str | None = None
    """
    The date this Block Storage was created.
    """
    id: str | None = None
    """
    A unique ID for the Block Storage.
    """
    label: str | None = None
    """
    The user-supplied label.
    """
    mountId: str | None = None
    """
    An ID associated with the instance, when mounted the ID can be found in /dev/disk/by-id prefixed with virtio.
    """
    osId: int | None = None
    """
    Operating system ID, if applicable.
    """
    pendingCharges: float | None = None
    """
    Charges due for this subscription at the end of the billing period.
    """
    region: str | None = None
    """
    The Region id where the Block Storage is located.
    """
    sizeGb: int | None = None
    """
    Size of the Block Storage in GB.
    """
    snapshotId: str | None = None
    """
    The snapshot_id from which this block device was cloned.
    """
    status: str | None = None
    """
    The current status of this Block Storage.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    """
    AtProvider holds the observed values from the Vultr API.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Blockstorage(BaseModel):
    apiVersion: Literal['vultr.m.crossplane.io/v1alpha1'] | None = (
        'vultr.m.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Blockstorage'] | None = 'Blockstorage'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    BlockstorageSpec defines the desired state of Blockstorage.
    """
    status: Status | None = None
    """
    BlockstorageStatus defines the observed state of Blockstorage.
    """


class BlockstorageList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Blockstorage]
    """
    List of blockstorages. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """