# generated by datamodel-codegen:
#   filename:  workdir/vultr_m_crossplane_io_v1alpha1_firewallrule.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class FirewallGroupIDRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class FirewallGroupIDSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    firewallGroupIDRef: FirewallGroupIDRef | None = None
    """
    A NamespacedReference to a named object.
    """
    firewallGroupIDSelector: FirewallGroupIDSelector | None = None
    """
    NamespacedSelector selects a namespaced object.
    """
    firewallGroupId: str | None = None
    """
    The id of the parent Firewall Group this rule belongs to. Populates the {firewall-group-id} path parameter; not part of the firewall_rule response body.
    """
    ipType: Literal['v4', 'v6']
    """
    The type of IP rule.
    """
    notes: str | None = None
    """
    User-supplied notes for this rule.
    """
    port: str | None = None
    """
    TCP/UDP only. A specific port or a colon-separated port range (e.g. "80" or "8000:8080").
    """
    protocol: Literal['icmp', 'tcp', 'udp', 'gre', 'esp', 'ah']
    """
    The protocol for this rule.
    """
    source: str | None = None
    """
    If given the value "cloudflare", subnet and subnetSize are both ignored and Cloudflare's IP space is allowed through the firewall. A Load Balancer id may also be supplied to use its IPs. Empty string uses the value from subnet/subnetSize.
    """
    subnet: str
    """
    IP address representing a subnet. The IP address format must match the ipType value.
    """
    subnetSize: int
    """
    The number of bits for the netmask in CIDR notation. Example: 24.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    """
    ForProvider holds the user-supplied parameters for this FirewallRule.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    action: str | None = None
    """
    Action to take when this rule is met. Vultr only supports "accept" rules.
    """
    firewallGroupId: str | None = None
    """
    The id of the parent Firewall Group this rule belongs to. Populates the {firewall-group-id} path parameter; not part of the firewall_rule response body.
    """
    id: str | None = None
    """
    A unique, server-assigned ID for the Firewall Rule. The Vultr API returns this as a JSON integer; the controller converts int<->string at the API boundary so the external-name annotation and AtProvider.ID stay string-typed.
    """
    ipType: str | None = None
    """
    The type of IP rule.
    """
    notes: str | None = None
    """
    User-supplied notes for this rule.
    """
    port: str | None = None
    """
    TCP/UDP only. A specific port or a colon-separated port range (e.g. "80" or "8000:8080").
    """
    protocol: str | None = None
    """
    The protocol for this rule.
    """
    source: str | None = None
    """
    If given the value "cloudflare", subnet and subnetSize are both ignored and Cloudflare's IP space is allowed through the firewall. A Load Balancer id may also be supplied to use its IPs. Empty string uses the value from subnet/subnetSize.
    """
    subnet: str | None = None
    """
    IP address representing a subnet. The IP address format must match the ipType value.
    """
    subnetSize: int | None = None
    """
    The number of bits for the netmask in CIDR notation. Example: 24.
    """
    type: str | None = None
    """
    Deprecated alias of ipType, returned by the API for backward compatibility.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    """
    AtProvider holds the observed values from the Vultr API.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class FirewallRule(BaseModel):
    apiVersion: Literal['vultr.m.crossplane.io/v1alpha1'] | None = (
        'vultr.m.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['FirewallRule'] | None = 'FirewallRule'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    FirewallRuleSpec defines the desired state of FirewallRule.
    """
    status: Status | None = None
    """
    FirewallRuleStatus defines the observed state of FirewallRule.
    """


class FirewallRuleList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[FirewallRule]
    """
    List of firewallrules. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """