apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: models.modelplane.ai
spec:
  compositeTypeRef:
    apiVersion: modelplane.ai/v1alpha1
    kind: Model
  mode: Pipeline
  pipeline:
  - functionRef:
      name: negzupboundio-modelplane-infracompose-model
    step: compose-model
