# generated by datamodel-codegen:
#   filename:  workdir/infrastructure_modelplane_ai_v1alpha1_k3scluster.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, conint, constr

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class SecretRef(BaseModel):
    key: constr(min_length=1, max_length=253) | None = 'ssh-privatekey'
    """
    Key within the Secret that holds the private key.
    """
    name: constr(min_length=1, max_length=253)
    """
    Name of the Secret.
    """


class Auth(BaseModel):
    secretRef: SecretRef
    """
    Secret holding the SSH private key, in the same namespace as this K3sCluster.
    """
    username: constr(min_length=1, max_length=63) | None = 'root'
    """
    SSH user. Must be root or have passwordless sudo.
    """


class ControlPlane(BaseModel):
    host: constr(min_length=1, max_length=253)
    """
    DNS name or IP address of the machine.
    """
    port: conint(ge=1, le=65535) | None = 22
    """
    SSH port.
    """


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Version(BaseModel):
    channel: constr(min_length=1, max_length=32) | None = None
    """
    k3s release channel (e.g. stable, v1.34). Installs the channel's latest release.
    """
    version: constr(min_length=1, max_length=32) | None = None
    """
    Exact k3s version to install (e.g. v1.34.1+k3s1).
    """


class Taint(BaseModel):
    effect: Literal['NoSchedule', 'PreferNoSchedule', 'NoExecute']
    key: constr(min_length=1, max_length=253)
    value: constr(max_length=63) | None = None


class Worker(BaseModel):
    host: constr(min_length=1, max_length=253)
    """
    DNS name or IP address of the machine.
    """
    labels: dict[str, str] | None = None
    """
    Node labels applied to this worker.
    """
    name: constr(min_length=1, max_length=63)
    """
    Unique name for this worker.
    """
    port: conint(ge=1, le=65535) | None = 22
    """
    SSH port.
    """
    taints: list[Taint] | None = Field(None, max_length=8)
    """
    Node taints applied to this worker.
    """


class Spec(BaseModel):
    auth: Auth
    """
    SSH authentication used to reach every machine. All machines must accept the same user and private key.
    """
    controlPlane: ControlPlane
    """
    The machine that runs the k3s server (the management plane). Must be reachable over SSH from the control plane running Modelplane.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    version: Version | None = None
    """
    The k3s release to install. Defaults to the v1.34 channel, the first where Dynamic Resource Allocation (how GPUs bind to pods) is generally available.
    """
    workers: list[Worker] | None = Field(None, max_length=64)
    """
    Machines that join the cluster as k3s agents (the worker plane). Labels and taints are applied at registration time via k3s agent arguments.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Secret(BaseModel):
    key: constr(max_length=253)
    """
    Key within the Secret that holds the credential data.
    """
    name: constr(max_length=253)
    """
    Name of the Secret.
    """
    type: Literal['Kubeconfig'] = 'Kubeconfig'
    """
    The type of credential this secret contains. Kubeconfig contains a kubeconfig file with the cluster endpoint, CA certificate, and a static client certificate.
    """


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    secrets: list[Secret] | None = None
    """
    Secrets produced by this cluster. Consumers use these to authenticate to the cluster. All secrets are in the same namespace as this K3sCluster.
    """


class K3sCluster(BaseModel):
    apiVersion: Literal['infrastructure.modelplane.ai/v1alpha1'] | None = (
        'infrastructure.modelplane.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['K3sCluster'] | None = 'K3sCluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    K3sClusterSpec defines the desired state of K3sCluster.
    """
    status: Status | None = None
    """
    K3sClusterStatus defines the observed state of K3sCluster.
    """


class K3sClusterList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[K3sCluster]
    """
    List of k3sclusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """