# generated by datamodel-codegen:
#   filename:  workdir/vultr_crossplane_io_v1alpha1_vkecluster.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ....k8s.apimachinery.pkg.apis.meta import v1


class Node(BaseModel):
    dateCreated: str | None = None
    """
    Date of creation.
    """
    id: str | None = None
    """
    ID of the nodepool instance.
    """
    label: str | None = None
    """
    Label of the nodepool instance.
    """
    status: str | None = None
    """
    Status of the nodepool instance.
    """


class Taint(BaseModel):
    effect: str | None = None
    """
    Effect of the taint.
    """
    id: str | None = None
    """
    ID of the taint.
    """
    key: str | None = None
    """
    Key of the taint.
    """
    value: str | None = None
    """
    Value of the taint.
    """


class NodePool(BaseModel):
    autoScaler: bool | None = None
    """
    Option to use the auto scaler with this nodepool. Defaults to false.
    """
    dateCreated: str | None = None
    """
    Date the nodepool was created.
    """
    dateUpdated: str | None = None
    """
    Date the nodepool was updated.
    """
    id: str | None = None
    """
    The NodePool id.
    """
    label: str | None = None
    """
    Label for this nodepool. Cannot be changed after the nodepool is created. Cannot duplicate another node pool label in the same cluster.
    """
    labels: dict[str, str] | None = None
    """
    Map of key/value pairs defining labels to automatically apply to all nodes in this nodepool.
    """
    maxNodes: int | None = None
    """
    Auto scaler field for the maximum nodes for this nodepool. Defaults to 1.
    """
    minNodes: int | None = None
    """
    Auto scaler field for the minimum nodes for this nodepool. Defaults to 1.
    """
    nodeQuantity: int | None = None
    """
    Number of instances to deploy in this nodepool. Minimum of 1 node required, but at least 3 is recommended.
    """
    nodes: list[Node] | None = None
    """
    Instances that belong to this nodepool.
    """
    plan: str | None = None
    """
    Plan used for this nodepool. Minimum plan must be $10.
    """
    status: str | None = None
    """
    Status for this nodepool.
    """
    tag: str | None = None
    """
    Tag for this nodepool.
    """
    taints: list[Taint] | None = None
    """
    Kubernetes taints applied to all nodes in this nodepool.
    """
    userData: str | None = None
    """
    The user-supplied, base64 encoded user data for all nodes in this nodepool (only applied on nodes created after user data is set).
    """
    vpcOnly: bool | None = None
    """
    Requires the cluster to have a VPC with an active NAT Gateway subscription. If true, instances in this node pool will not receive a public IP or public NIC and will reach the internet via the NAT Gateway attached to the VPC.
    """


class Oidc(BaseModel):
    clientId: str | None = None
    """
    The unique identifier assigned to your application by the OIDC provider.
    """
    groupsClaim: str | None = None
    """
    The claim in the OIDC token that contains the user's group memberships.
    """
    issuerUrl: str | None = None
    """
    The URL of the OIDC provider that issues authentication tokens.
    """
    usernameClaim: str | None = None
    """
    The claim in the OIDC token that identifies the end user's username.
    """


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class VpcIDRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpcIDSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    enableFirewall: bool | None = None
    """
    Whether a Firewall Group should be deployed and managed by this cluster. Defaults to false.
    """
    haControlplanes: bool | None = None
    """
    Whether a highly available control planes configuration has been deployed. Defaults to false.
    """
    label: str
    """
    The label for your Kubernetes cluster.
    """
    nodePools: list[NodePool] | None = None
    """
    NodePools in this cluster.
    """
    oidc: Oidc | None = None
    """
    The OpenID Connect (OIDC) configuration for this VKE cluster.
    """
    region: str
    """
    Region you want to deploy VKE in.
    """
    version: str
    """
    Version of Kubernetes you want to deploy.
    """
    vpcIDRef: VpcIDRef | None = None
    """
    A Reference to a named object.
    """
    vpcIDSelector: VpcIDSelector | None = None
    """
    A Selector selects an object.
    """
    vpcId: str | None = None
    """
    The VPC id to use when deploying this VKE. Omitting or leaving this empty will configure a new VPC network with this deployment.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    """
    ForProvider holds the user-supplied parameters for this VkeCluster.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class Vpc(BaseModel):
    id: str | None = None
    """
    The ID of the VPC Network.
    """
    subnet: str | None = None
    """
    The IP subnet used for the instance on the VPC Network.
    """
    version: int | None = None
    """
    The version of VPC (1 or 2). Deprecated.
    """


class AtProvider(BaseModel):
    clusterSubnet: str | None = None
    """
    IP range that your pods will run on in this cluster.
    """
    dateCreated: str | None = None
    """
    Date of creation.
    """
    enableFirewall: bool | None = None
    """
    Whether a Firewall Group should be deployed and managed by this cluster. Defaults to false.
    """
    endpoint: str | None = None
    """
    Domain for your Kubernetes Clusters Control Plane.
    """
    firewallGroupId: str | None = None
    """
    The Firewall Group id linked to this cluster.
    """
    haControlplanes: bool | None = None
    """
    Whether a highly available control planes configuration has been deployed. Defaults to false.
    """
    id: str | None = None
    """
    ID for the VKE cluster.
    """
    ip: str | None = None
    """
    IP for your Kubernetes Clusters Control Plane.
    """
    label: str | None = None
    """
    The label for your Kubernetes cluster.
    """
    nodePools: list[NodePool] | None = None
    """
    NodePools in this cluster.
    """
    oidc: Oidc | None = None
    """
    The OpenID Connect (OIDC) configuration for this VKE cluster.
    """
    region: str | None = None
    """
    Region you want to deploy VKE in.
    """
    serviceSubnet: str | None = None
    """
    IP range that services will run on this cluster.
    """
    status: str | None = None
    """
    Status for VKE cluster.
    """
    version: str | None = None
    """
    Version of Kubernetes you want to deploy.
    """
    vpcId: str | None = None
    """
    The VPC id to use when deploying this VKE. Omitting or leaving this empty will configure a new VPC network with this deployment.
    """
    vpcs: list[Vpc] | None = None
    """
    List of VPC Networks to which the instance is attached.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    """
    AtProvider holds the observed values from the Vultr API.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class VkeCluster(BaseModel):
    apiVersion: Literal['vultr.crossplane.io/v1alpha1'] | None = (
        'vultr.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['VkeCluster'] | None = 'VkeCluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    VkeClusterSpec defines the desired state of VkeCluster.
    """
    status: Status | None = None
    """
    VkeClusterStatus defines the observed state of VkeCluster.
    """


class VkeClusterList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[VkeCluster]
    """
    List of vkeclusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """