apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: modeldeployments.modelplane.ai
spec:
  compositeTypeRef:
    apiVersion: modelplane.ai/v1alpha1
    kind: ModelDeployment
  mode: Pipeline
  pipeline:
  - functionRef:
      name: negzupboundio-modelplane-infracompose-model-deployment
    step: compose-model-deployment
    requirements:
      requiredResources:
      - requirementName: gateway
        apiVersion: gateway.networking.k8s.io/v1
        kind: Gateway
        name: modelplane
        namespace: modelplane-system
