# generated by datamodel-codegen:
#   filename:  workdir/vultr_m_crossplane_io_v1alpha1_role.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class ForProvider(BaseModel):
    description: str | None = None
    """
    A description of the role.
    """
    maxSessionDuration: int | None = None
    """
    Maximum session duration in seconds. Default is 3600.
    """
    name: str
    """
    The role name.
    """
    roleType: Literal['assumable', 'assignable']
    """
    The role type. API-side default is `assumable` (corrects the OpenAPI spec's stale `user`/`service` enum, which the API rejects with 422).
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    """
    ForProvider holds the user-supplied parameters for this Role.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class Policy(BaseModel):
    assignedBy: str | None = None
    """
    The user ID that assigned this Policy to the Role.
    """
    dateAssigned: str | None = None
    """
    Date the Policy was assigned to the Role.
    """
    policyId: str | None = None
    """
    The unique ID of the attached Policy.
    """
    policyName: str | None = None
    """
    The name of the attached Policy.
    """
    roleDescription: str | None = None
    """
    The description of the Role (self-reference, as returned by the API).
    """
    roleId: str | None = None
    """
    The unique ID of the Role (self-reference, as returned by the API).
    """
    roleName: str | None = None
    """
    The name of the Role (self-reference, as returned by the API).
    """
    roleType: str | None = None
    """
    The role type of the Role (self-reference, as returned by the API).
    """


class AtProvider(BaseModel):
    dateCreated: str | None = None
    """
    Date the Role was originally created.
    """
    description: str | None = None
    """
    A description of the role.
    """
    id: str | None = None
    """
    A unique ID for the Role.
    """
    maxSessionDuration: int | None = None
    """
    Maximum session duration in seconds. Default is 3600.
    """
    name: str | None = None
    """
    The role name.
    """
    policies: list[Policy] | None = None
    """
    Policies attached to this Role. Response-only — not proven settable on create.
    """
    roleType: str | None = None
    """
    The role type. API-side default is `assumable` (corrects the OpenAPI spec's stale `user`/`service` enum, which the API rejects with 422).
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    """
    AtProvider holds the observed values from the Vultr API.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Role(BaseModel):
    apiVersion: Literal['vultr.m.crossplane.io/v1alpha1'] | None = (
        'vultr.m.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Role'] | None = 'Role'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    RoleSpec defines the desired state of Role.
    """
    status: Status | None = None
    """
    RoleStatus defines the observed state of Role.
    """


class RoleList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Role]
    """
    List of roles. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """