# generated by datamodel-codegen:
#   filename:  workdir/infrastructure_modelplane_ai_v1alpha1_vultrbaremetalcluster.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, conint, constr

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class Credentials(BaseModel):
    name: constr(min_length=1, max_length=253) | None = 'default'
    type: Literal['ProviderConfig', 'ClusterProviderConfig'] | None = (
        'ClusterProviderConfig'
    )


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class K3s(BaseModel):
    channel: constr(min_length=1, max_length=32) | None = 'v1.34'
    """
    k3s release channel. Defaults to the first channel where Dynamic Resource Allocation (how GPUs bind to pods) is generally available.
    """


class Management(BaseModel):
    osId: int | None = 2284
    """
    Vultr operating system ID installed on the server. Defaults to Ubuntu 24.04 LTS x64; list IDs with vultr-cli os list.
    """
    plan: constr(min_length=1, max_length=63) | None = 'vbm-6c-32gb-amd'
    """
    Vultr bare metal plan for the management server. The default is a CPU-only plan available in most regions that offer bare metal.
    """


class Gpu(BaseModel):
    acceleratorType: constr(min_length=1, max_length=63)
    """
    GPU accelerator type (e.g. amd-mi355x). Used to label the pool's nodes; the actual GPU and count are determined by the plan.
    """


class NodePool(BaseModel):
    gpu: Gpu
    """
    GPU configuration.
    """
    name: constr(min_length=1, max_length=40)
    """
    Unique name for this pool.
    """
    nodeCount: conint(ge=1, le=64) | None = 1
    """
    Number of servers in this pool.
    """
    osId: int | None = None
    """
    Vultr operating system ID for the pool's servers. Defaults to the management server's osId.
    """
    plan: constr(min_length=1, max_length=63)
    """
    Vultr bare metal plan ID for the pool's servers (e.g. vbm-256c-3072gb-8-mi355x-gpu).
    """


class SecretRef(BaseModel):
    name: constr(min_length=1, max_length=253)
    """
    Name of the Secret.
    """
    privateKeyKey: constr(min_length=1, max_length=253) | None = 'ssh-privatekey'
    """
    Key within the Secret that holds the private key.
    """
    publicKeyKey: constr(min_length=1, max_length=253) | None = 'ssh-publickey'
    """
    Key within the Secret that holds the public key.
    """


class Ssh(BaseModel):
    secretRef: SecretRef
    """
    Secret holding the SSH key pair, in the same namespace as this VultrBaremetalCluster.
    """
    username: constr(min_length=1, max_length=63) | None = 'root'
    """
    SSH user the servers accept the key for. Vultr installs keys for root by default.
    """


class Spec(BaseModel):
    credentials: Credentials | None = None
    """
    Vultr ProviderConfig or ClusterProviderConfig used to authenticate to the Vultr API. Defaults to the ClusterProviderConfig named default.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    k3s: K3s | None = Field({}, validate_default=True)
    """
    The k3s release installed on the servers.
    """
    management: Management | None = Field({}, validate_default=True)
    """
    The CPU-only bare metal server that runs the k3s server (the management plane).
    """
    nodePools: list[NodePool] = Field(..., max_length=8, min_length=1)
    """
    GPU bare metal pools that join the cluster as workers. Fixed size; Vultr bare metal has no autoscaling.
    """
    region: constr(min_length=1, max_length=32)
    """
    Vultr region for all servers (e.g. ewr, ord). Bare metal plan availability varies by region; check with vultr-cli plans list --type vbm.
    """
    ssh: Ssh
    """
    SSH key pair used to reach the servers. The public key is registered with Vultr and installed on every server; the private key drives the k3s install over SSH.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Secret(BaseModel):
    key: constr(max_length=253)
    """
    Key within the Secret that holds the credential data.
    """
    name: constr(max_length=253)
    """
    Name of the Secret.
    """
    type: Literal['Kubeconfig'] = 'Kubeconfig'
    """
    The type of credential this secret contains. Kubeconfig contains a kubeconfig file with the cluster endpoint, CA certificate, and a static client certificate.
    """


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    secrets: list[Secret] | None = None
    """
    Secrets produced by this cluster. Consumers use these to authenticate to the cluster. All secrets are in the same namespace as this VultrBaremetalCluster.
    """


class VultrBaremetalCluster(BaseModel):
    apiVersion: Literal['infrastructure.modelplane.ai/v1alpha1'] | None = (
        'infrastructure.modelplane.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['VultrBaremetalCluster'] | None = 'VultrBaremetalCluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    VultrBaremetalClusterSpec defines the desired state of VultrBaremetalCluster.
    """
    status: Status | None = None
    """
    VultrBaremetalClusterStatus defines the observed state of VultrBaremetalCluster.
    """


class VultrBaremetalClusterList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[VultrBaremetalCluster]
    """
    List of vultrbaremetalclusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """