# Copyright 2026 The Modelplane Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate the serving stack requirements docs page and e2e inputs.

Renders, from the requirement data the component lists carry
(function/stacks/):

- docs/content/platform/serving-stack-requirements.md: per substrate
  component, what Modelplane would install in Managed mode, what a
  Provided cluster must supply in its place, what nothing can check,
  and what users can skip.
- e2e/provided/: the Standard substrate as helm inputs (charts.tsv,
  values/<key>.yaml) and raw manifests, so the Provided-mode e2e
  (`nix run .#e2e -- --provided`) pre-installs exactly the versions and
  values Modelplane would, without a second copy of the pins.

The docs, the e2e inputs, and the Provided-mode checks in
compose-serving-stack all read the same data, so they can't drift; the
requirements-doc-current flake check regenerates these outputs and
fails on a stale or hand-edited copy. Run via
`nix run .#requirements-doc`.
"""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import yaml
from function import stacks
from function.stacks.components import (
    Chart,
    Component,
    RequiredCRD,
    RequiredObject,
)

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "content" / "platform" / "serving-stack-requirements.md"
E2E = ROOT / "e2e" / "provided"

GENERATED_BANNER = (
    "# Generated by functions/compose-serving-stack/requirements_doc.py\n"
    "# from the serving stack component lists. Do not edit; run\n"
    "# `nix run .#requirements-doc` after changing the stack data.\n"
)

HEADER = """\
---
title: Serving Stack Requirements
weight: 35
description: What an existing cluster must provide to run the serving stack itself.
---
<!-- Generated by functions/compose-serving-stack/requirements_doc.py
     from the serving stack component lists. Do not edit; run
     `nix run .#requirements-doc` after changing the stack data. -->
An `InferenceCluster` with `spec.cluster.existing.components: Provided`
installs no serving stack components. The cluster provides the whole
substrate itself, and Modelplane only verifies it and composes its own
configuration on top. This page lists what that cluster must provide,
per component Modelplane would otherwise install. It applies on top of
the general [requirements for an existing
cluster]({{< ref "/platform/inference-cluster.md" >}}).

Modelplane checks the **checked** entries continuously and reports what
is missing through the `RequirementsMet` condition on the
`InferenceCluster`. A check verifies presence and served API versions,
not the installed release: the **not checked** entries, including
component versions, are yours to meet. The version listed per component
is the one Modelplane installs in Managed mode and tests against; stay
close to it.
"""

FOOTER = """\
## What Modelplane still installs

Provided mode only skips the substrate. Modelplane still composes its
own configuration and workloads: the `modelplane-system` namespace, the
`EnvoyProxy`, `GatewayClass` and `Gateway` for the inference gateway,
and on the Dynamo stack its KAI `Queue` hierarchy and the ModelExpress
server with its CRDs. Their substrate dependencies gate on the checks
above, so none of them is applied before the cluster serves the APIs
they need.

During deletion, Modelplane can't order its configuration ahead of a
substrate it doesn't own. Keep your controllers (the gateway
controller, KAI) running while an `InferenceCluster` deletes, so they
can process finalizers on Modelplane's configuration.
"""


def _requirement_line(r: RequiredCRD | RequiredObject) -> str:
    if isinstance(r, RequiredCRD):
        versions = " or ".join(f"`{v}`" for v in r.versions)
        return f"CRD `{r.name}` serving {versions}"
    return f"`{r.kind}` `{r.name}` (`{r.api_version}`)"


def _component_section(c: Component) -> list[str]:
    # The heading is the component key in a code span: keys are stable
    # identity (and stable anchors), and Vale skips code spans, so
    # lowercase keys like kai-scheduler don't trip its brand-name rules.
    lines = [f"### `{c.key}`", ""]
    if isinstance(c, Chart):
        lines.append(f"Managed mode installs chart `{c.chart}` `{c.version}`.")
    else:
        lines.append("Managed mode applies manifests Modelplane vendors from the upstream release.")
    lines.append("")
    if c.requires:
        lines.append("Checked:")
        lines.append("")
        lines.extend(f"- {_requirement_line(r)}" for r in c.requires)
        lines.append("")
    if c.unchecked:
        lines.append("Not checked:")
        lines.append("")
        lines.extend(f"- {note}" for note in c.unchecked)
        lines.append("")
    if c.not_needed:
        lines.append("Not needed:")
        lines.append("")
        lines.extend(f"- {note}" for note in c.not_needed)
        lines.append("")
    if isinstance(c, Chart) and c.key == "envoy-gateway" and c.values:
        lines.append(
            "The exact values Modelplane installs the chart with. The"
            " `extensionManager` wiring is the one coupling no check can"
            " verify. Without it, routes to an `InferencePool` never"
            " route while every component looks healthy:"
        )
        lines.append("")
        lines.append("```yaml")
        lines.append(yaml.safe_dump(c.values, default_flow_style=False, sort_keys=False).rstrip())
        lines.append("```")
        lines.append("")
    return lines


def render() -> str:
    standard = stacks.join("Existing", "Standard")
    dynamo = stacks.join("Existing", "Dynamo")
    standard_keys = {c.key for c in standard}
    dynamo_keys = {c.key for c in dynamo}

    shared = [c for c in standard if c.role == "substrate" and c.key in dynamo_keys]
    standard_only = [c for c in standard if c.role == "substrate" and c.key not in dynamo_keys]
    dynamo_only = [c for c in dynamo if c.role == "substrate" and c.key not in standard_keys]

    lines = [HEADER]
    lines.append("## On every stack")
    lines.append("")
    for c in shared:
        lines.extend(_component_section(c))
    lines.append("## Standard stack")
    lines.append("")
    for c in standard_only:
        lines.extend(_component_section(c))
    lines.append("## Dynamo stack")
    lines.append("")
    for c in dynamo_only:
        lines.extend(_component_section(c))
    lines.append(FOOTER)
    return "\n".join(lines)


def write_e2e() -> list[pathlib.Path]:
    """Write the Standard substrate as e2e pre-install inputs.

    charts.tsv carries one substrate chart per line, in stack data
    order (which is dependency order: cert-manager before the gateway
    that needs its webhooks), values/<key>.yaml the chart's values
    verbatim, and manifests.yaml the substrate's raw manifests (the
    vendored GAIE CRDs). run.sh loops helm over them with non-mp
    release names, proving Modelplane composes against a substrate it
    doesn't own.
    """
    written: list[pathlib.Path] = []
    values_dir = E2E / "values"
    values_dir.mkdir(parents=True, exist_ok=True)
    for stale in values_dir.glob("*.yaml"):
        stale.unlink()

    rows: list[str] = []
    manifests: list[dict] = []
    for c in stacks.join("Existing", "Standard"):
        if c.role != "substrate":
            continue
        if isinstance(c, Chart):
            rows.append("\t".join((c.key, c.chart, c.repository, c.version, c.namespace, str(c.wait).lower())))
            if c.values:
                out = values_dir / f"{c.key}.yaml"
                out.write_text(GENERATED_BANNER + yaml.safe_dump(c.values, default_flow_style=False, sort_keys=False))
                written.append(out)
        else:
            manifests.extend(c.manifests)

    charts = E2E / "charts.tsv"
    charts.write_text(GENERATED_BANNER + "\n".join(rows) + "\n")
    written.append(charts)
    out = E2E / "manifests.yaml"
    out.write_text(GENERATED_BANNER + yaml.safe_dump_all(manifests, default_flow_style=False, sort_keys=False))
    written.append(out)
    return written


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)}")
    for path in write_e2e():
        print(f"wrote {path.relative_to(ROOT)}")
