# generated by datamodel-codegen:
#   filename:  workdir/efs_aws_m_upbound_io_v1beta1_filesystem.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ......k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class KmsKeyIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class KmsKeyIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class LifecyclePolicyItem(BaseModel):
    transitionToArchive: str | None = None
    """
    Indicates how long it takes to transition files to the archive storage class. Requires transition_to_ia, Elastic Throughput and General Purpose performance mode. Valid values: AFTER_1_DAY, AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS, AFTER_90_DAYS, AFTER_180_DAYS, AFTER_270_DAYS, or AFTER_365_DAYS.
    """
    transitionToIa: str | None = None
    """
    Indicates how long it takes to transition files to the IA storage class. Valid values: AFTER_1_DAY, AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS, AFTER_90_DAYS, AFTER_180_DAYS, AFTER_270_DAYS, or AFTER_365_DAYS.
    """
    transitionToPrimaryStorageClass: str | None = None
    """
    Describes the policy used to transition a file from infequent access storage to primary storage. Valid values: AFTER_1_ACCESS.
    """


class Protection(BaseModel):
    replicationOverwrite: str | None = None
    """
    Indicates whether replication overwrite protection is enabled. Valid values: ENABLED or DISABLED.
    """


class ForProvider(BaseModel):
    availabilityZoneName: str | None = None
    """
    the AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes. See user guide for more information.
    """
    creationToken: str | None = None
    """
    A unique name (a maximum of 64 characters are allowed)
    used as reference when creating the Elastic File System to ensure idempotent file
    system creation. See Elastic File System
    user guide for more information.
    """
    encrypted: bool | None = None
    """
    If true, the disk will be encrypted.
    """
    kmsKeyId: str | None = None
    """
    The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true.
    """
    kmsKeyIdRef: KmsKeyIdRef | None = None
    """
    Reference to a Key in kms to populate kmsKeyId.
    """
    kmsKeyIdSelector: KmsKeyIdSelector | None = None
    """
    Selector for a Key in kms to populate kmsKeyId.
    """
    lifecyclePolicy: list[LifecyclePolicyItem] | None = None
    """
    A file system lifecycle policy object. See lifecycle_policy block below for details.
    """
    performanceMode: str | None = None
    """
    The file system performance mode. Can be either "generalPurpose" or "maxIO" (Default: "generalPurpose").
    """
    protection: Protection | None = None
    """
    A file system protection object. See protection block below for details.
    """
    provisionedThroughputInMibps: float | None = None
    """
    The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned.
    """
    region: str
    """
    Region where this resource will be managed. Defaults to the Region set in the provider configuration.
    Region is the region you'd like your resource to be created in.
    """
    tags: dict[str, str] | None = None
    """
    Key-value map of resource tags.
    """
    throughputMode: str | None = None
    """
    Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned, or elastic. When using provisioned, also set provisioned_throughput_in_mibps.
    """


class InitProvider(BaseModel):
    availabilityZoneName: str | None = None
    """
    the AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes. See user guide for more information.
    """
    creationToken: str | None = None
    """
    A unique name (a maximum of 64 characters are allowed)
    used as reference when creating the Elastic File System to ensure idempotent file
    system creation. See Elastic File System
    user guide for more information.
    """
    encrypted: bool | None = None
    """
    If true, the disk will be encrypted.
    """
    kmsKeyId: str | None = None
    """
    The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true.
    """
    kmsKeyIdRef: KmsKeyIdRef | None = None
    """
    Reference to a Key in kms to populate kmsKeyId.
    """
    kmsKeyIdSelector: KmsKeyIdSelector | None = None
    """
    Selector for a Key in kms to populate kmsKeyId.
    """
    lifecyclePolicy: list[LifecyclePolicyItem] | None = None
    """
    A file system lifecycle policy object. See lifecycle_policy block below for details.
    """
    performanceMode: str | None = None
    """
    The file system performance mode. Can be either "generalPurpose" or "maxIO" (Default: "generalPurpose").
    """
    protection: Protection | None = None
    """
    A file system protection object. See protection block below for details.
    """
    provisionedThroughputInMibps: float | None = None
    """
    The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned.
    """
    tags: dict[str, str] | None = None
    """
    Key-value map of resource tags.
    """
    throughputMode: str | None = None
    """
    Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned, or elastic. When using provisioned, also set provisioned_throughput_in_mibps.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class SizeInByte(BaseModel):
    value: float | None = None
    """
    The latest known metered size (in bytes) of data stored in the file system.
    """
    valueInIa: float | None = None
    """
    The latest known metered size (in bytes) of data stored in the Infrequent Access storage class.
    """
    valueInStandard: float | None = None
    """
    The latest known metered size (in bytes) of data stored in the Standard storage class.
    """


class AtProvider(BaseModel):
    arn: str | None = None
    """
    Amazon Resource Name of the file system.
    """
    availabilityZoneId: str | None = None
    """
    The identifier of the Availability Zone in which the file system's One Zone storage classes exist.
    """
    availabilityZoneName: str | None = None
    """
    the AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes. See user guide for more information.
    """
    creationToken: str | None = None
    """
    A unique name (a maximum of 64 characters are allowed)
    used as reference when creating the Elastic File System to ensure idempotent file
    system creation. See Elastic File System
    user guide for more information.
    """
    dnsName: str | None = None
    """
    The DNS name for the filesystem per documented convention.
    """
    encrypted: bool | None = None
    """
    If true, the disk will be encrypted.
    """
    id: str | None = None
    """
    The ID that identifies the file system (e.g., fs-ccfc0d65).
    """
    kmsKeyId: str | None = None
    """
    The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true.
    """
    lifecyclePolicy: list[LifecyclePolicyItem] | None = None
    """
    A file system lifecycle policy object. See lifecycle_policy block below for details.
    """
    name: str | None = None
    """
    The value of the file system's Name tag.
    """
    numberOfMountTargets: float | None = None
    """
    The current number of mount targets that the file system has.
    """
    ownerId: str | None = None
    """
    The AWS account that created the file system. If the file system was createdby an IAM user, the parent account to which the user belongs is the owner.
    """
    performanceMode: str | None = None
    """
    The file system performance mode. Can be either "generalPurpose" or "maxIO" (Default: "generalPurpose").
    """
    protection: Protection | None = None
    """
    A file system protection object. See protection block below for details.
    """
    provisionedThroughputInMibps: float | None = None
    """
    The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned.
    """
    region: str | None = None
    """
    Region where this resource will be managed. Defaults to the Region set in the provider configuration.
    Region is the region you'd like your resource to be created in.
    """
    sizeInBytes: list[SizeInByte] | None = None
    """
    The latest known metered size (in bytes) of data stored in the file system, the value is not the exact size that the file system was at any point in time. See Size In Bytes.
    """
    tags: dict[str, str] | None = None
    """
    Key-value map of resource tags.
    """
    tagsAll: dict[str, str] | None = None
    """
    A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
    """
    throughputMode: str | None = None
    """
    Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned, or elastic. When using provisioned, also set provisioned_throughput_in_mibps.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class FileSystem(BaseModel):
    apiVersion: Literal['efs.aws.m.upbound.io/v1beta1'] | None = (
        'efs.aws.m.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['FileSystem'] | None = 'FileSystem'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    FileSystemSpec defines the desired state of FileSystem
    """
    status: Status | None = None
    """
    FileSystemStatus defines the observed state of FileSystem.
    """


class FileSystemList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[FileSystem]
    """
    List of filesystems. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """