# generated by datamodel-codegen:
#   filename:  workdir/vultr_m_crossplane_io_v1alpha1_database.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class VpcIDRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpcIDSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    backupHour: str | None = None
    """
    The chosen hour (UTC) for daily backups to take place. Excluded for Kafka engine types.
    """
    backupMinute: str | None = None
    """
    The chosen minute of the backup hour for daily backups to take place. Excluded for Kafka engine types.
    """
    databaseEngine: Literal['mysql', 'pg', 'valkey', 'kafka']
    """
    The database engine type (MySQL, PostgreSQL, Valkey, Kafka). Immutable — the server silently ignores changes to this field on update.
    """
    databaseEngineVersion: str
    """
    The version number of the database engine in use (e.g. "16" for PostgreSQL). Immutable — the server silently ignores changes to this field on update.
    """
    enableKafkaConnect: bool | None = None
    """
    Configuration value for Kafka Connect support on the Managed Database (Kafka engine types only, business plans or higher).
    """
    enableKafkaRest: bool | None = None
    """
    Configuration value for Kafka REST support on the Managed Database (Kafka engine types only, business plans or higher).
    """
    enableSchemaRegistry: bool | None = None
    """
    Configuration value for Schema Registry support on the Managed Database (Kafka engine types only, business plans or higher).
    """
    evictionPolicy: str | None = None
    """
    The configured data eviction policy for Valkey engine types only.
    """
    label: str
    """
    The user-supplied label for this managed database.
    """
    maintenanceDow: (
        Literal[
            'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'
        ]
        | None
    ) = None
    """
    The chosen day of week for routine maintenance updates.
    """
    maintenanceTime: str | None = None
    """
    The chosen hour (UTC) for routine maintenance updates, in 24-hour HH:00 format (e.g. "01:00").
    """
    mysqlLongQueryTime: int | None = None
    """
    The number of seconds to denote a slow query when logging is enabled (MySQL engine types only).
    """
    mysqlRequirePrimaryKey: bool | None = None
    """
    Configuration value for requiring table primary keys (MySQL engine types only). A configuration toggle, NOT a connection secret.
    """
    mysqlSlowQueryLog: bool | None = None
    """
    Configuration value for slow query logging on the Managed Database (MySQL engine types only).
    """
    mysqlSqlModes: (
        list[
            Literal[
                'ALLOW_INVALID_DATES',
                'ANSI',
                'ANSI_QUOTES',
                'ERROR_FOR_DIVISION_BY_ZERO',
                'HIGH_NOT_PRECEDENCE',
                'IGNORE_SPACE',
                'NO_AUTO_VALUE_ON_ZERO',
                'NO_DIR_IN_CREATE',
                'NO_ENGINE_SUBSTITUTION',
                'NO_UNSIGNED_SUBTRACTION',
                'NO_ZERO_DATE',
                'NO_ZERO_IN_DATE',
                'ONLY_FULL_GROUP_BY',
                'PIPES_AS_CONCAT',
                'REAL_AS_FLOAT',
                'STRICT_ALL_TABLES',
                'STRICT_TRANS_TABLES',
                'TIME_TRUNCATE_FRACTIONAL',
                'TRADITIONAL',
            ]
        ]
        | None
    ) = None
    """
    A list of names of enabled SQL Modes (MySQL engine types only).
    """
    plan: str
    """
    The name of the Managed Database plan (e.g. "vultr-dbaas-hobbyist-cc-1-25-1").
    """
    redisEvictionPolicy: str | None = None
    """
    The configured data eviction policy for Redis engine types only (legacy alias of evictionPolicy).
    """
    region: str
    """
    The Region id where the Managed Database is located. The server normalizes this to uppercase in responses.
    """
    tag: str | None = None
    """
    The user-supplied tag for this managed database.
    """
    trustedIps: list[str] | None = None
    """
    A list of trusted IP addresses for connecting to this Managed Database (in CIDR notation).
    """
    vpcIDRef: VpcIDRef | None = None
    """
    A NamespacedReference to a named object.
    """
    vpcIDSelector: VpcIDSelector | None = None
    """
    NamespacedSelector selects a namespaced object.
    """
    vpcId: str | None = None
    """
    The id of the VPC Network attached to the Managed Database.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    """
    ForProvider holds the user-supplied parameters for this Database.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class PgAvailableExtension(BaseModel):
    name: str | None = None
    """
    The name of the PostgreSQL extension.
    """
    versions: list[str] | None = None
    """
    The supported versions of this extension.
    """


class ReadReplica(BaseModel):
    dateCreated: str | None = None
    """
    The date this read replica was created.
    """
    dbname: str | None = None
    """
    The default database name on the read replica.
    """
    host: str | None = None
    """
    The connection hostname for the read replica.
    """
    id: str | None = None
    """
    A unique ID for the read replica.
    """
    label: str | None = None
    """
    The user-supplied label for the read replica.
    """
    password: str | None = None
    """
    The default user's password on the read replica.
    """
    port: str | None = None
    """
    The connection port for the read replica.
    """
    region: str | None = None
    """
    The region id where the read replica is located.
    """
    status: str | None = None
    """
    The current status of the read replica.
    """
    user: str | None = None
    """
    The default user configured on the read replica.
    """


class AtProvider(BaseModel):
    accessCert: str | None = None
    """
    The certificate to authenticate the default user (Kafka engine types only). Published as a connection secret.
    """
    accessKey: str | None = None
    """
    The private key to authenticate the default user (Kafka engine types only). Published as a connection secret.
    """
    backupHour: str | None = None
    """
    The chosen hour (UTC) for daily backups to take place. Excluded for Kafka engine types.
    """
    backupMinute: str | None = None
    """
    The chosen minute of the backup hour for daily backups to take place. Excluded for Kafka engine types.
    """
    caCertificate: str | None = None
    """
    The CA certificate for Managed Databases on this account. Published as a connection secret.
    """
    clusterTimeZone: str | None = None
    """
    The configured time zone of the Managed Database in TZ database format. Server-derived — NOT settable, despite the OpenAPI PUT request schema listing it.
    """
    databaseEngine: str | None = None
    """
    The database engine type (MySQL, PostgreSQL, Valkey, Kafka). Immutable — the server silently ignores changes to this field on update.
    """
    databaseEngineVersion: str | None = None
    """
    The version number of the database engine in use (e.g. "16" for PostgreSQL). Immutable — the server silently ignores changes to this field on update.
    """
    dateCreated: str | None = None
    """
    The date this database was created.
    """
    dbname: str | None = None
    """
    The default database name.
    """
    enableKafkaConnect: bool | None = None
    """
    Configuration value for Kafka Connect support on the Managed Database (Kafka engine types only, business plans or higher).
    """
    enableKafkaRest: bool | None = None
    """
    Configuration value for Kafka REST support on the Managed Database (Kafka engine types only, business plans or higher).
    """
    enableSchemaRegistry: bool | None = None
    """
    Configuration value for Schema Registry support on the Managed Database (Kafka engine types only, business plans or higher).
    """
    evictionPolicy: str | None = None
    """
    The configured data eviction policy for Valkey engine types only.
    """
    host: str | None = None
    """
    The public hostname for database connections, or private hostname if this managed database is attached to a VPC network. Published as a connection secret.
    """
    id: str | None = None
    """
    A unique ID for the Managed Database.
    """
    kafkaRestUri: str | None = None
    """
    The URI to access the RESTful interface of the Kafka cluster if Kafka REST is enabled. Modeled as string — the OpenAPI spec incorrectly declares this field `type: boolean`; corrected per the govultr v3 SDK and field description.
    """
    label: str | None = None
    """
    The user-supplied label for this managed database.
    """
    latestBackup: str | None = None
    """
    The date of the latest backup stored on the Managed Database.
    """
    maintenanceDow: str | None = None
    """
    The chosen day of week for routine maintenance updates.
    """
    maintenanceTime: str | None = None
    """
    The chosen hour (UTC) for routine maintenance updates, in 24-hour HH:00 format (e.g. "01:00").
    """
    mysqlLongQueryTime: int | None = None
    """
    The number of seconds to denote a slow query when logging is enabled (MySQL engine types only).
    """
    mysqlRequirePrimaryKey: bool | None = None
    """
    Configuration value for requiring table primary keys (MySQL engine types only). A configuration toggle, NOT a connection secret.
    """
    mysqlSlowQueryLog: bool | None = None
    """
    Configuration value for slow query logging on the Managed Database (MySQL engine types only).
    """
    mysqlSqlModes: list[str] | None = None
    """
    A list of names of enabled SQL Modes (MySQL engine types only).
    """
    password: str | None = None
    """
    The default user's secure password generated on creation. Published as a connection secret.
    """
    pendingCharges: float | None = None
    """
    Charges due for this subscription at the end of the billing period. Server-computed — NOT settable, despite the OpenAPI PUT request schema erroneously listing it.
    """
    pgAvailableExtensions: list[PgAvailableExtension] | None = None
    """
    The list of available PostgreSQL extensions (name and supported versions) for PostgreSQL engine types only.
    """
    plan: str | None = None
    """
    The name of the Managed Database plan (e.g. "vultr-dbaas-hobbyist-cc-1-25-1").
    """
    planBrokers: int | None = None
    """
    The number of brokers (Kafka engine types only).
    """
    planDisk: int | None = None
    """
    The size of the disk in GB (excluded for Valkey engine types).
    """
    planRam: int | None = None
    """
    The amount of RAM in MB.
    """
    planReplicas: int | None = None
    """
    The number of replica nodes (excluded for Kafka engine types).
    """
    planVcpus: int | None = None
    """
    The number of vCPUs.
    """
    port: str | None = None
    """
    The assigned port for connecting to the Managed Database. Published as a connection secret.
    """
    publicHost: str | None = None
    """
    The public hostname for database connections. Only present when the managed database is attached to a VPC network. Published as a connection secret.
    """
    readReplicas: list[ReadReplica] | None = None
    """
    The list of attached read-only replica nodes.
    """
    redisEvictionPolicy: str | None = None
    """
    The configured data eviction policy for Redis engine types only (legacy alias of evictionPolicy).
    """
    region: str | None = None
    """
    The Region id where the Managed Database is located. The server normalizes this to uppercase in responses.
    """
    saslPort: str | None = None
    """
    The port for connecting to the Managed Database via SASL (Kafka engine types only). Published as a connection secret.
    """
    schemaRegistryUri: str | None = None
    """
    The URI to access the Schema Registry service of the Kafka cluster if Schema Registry is enabled. Modeled as string — the OpenAPI spec incorrectly declares this field `type: boolean`; corrected per the govultr v3 SDK and field description.
    """
    status: str | None = None
    """
    The current status.
    """
    tag: str | None = None
    """
    The user-supplied tag for this managed database.
    """
    trustedIps: list[str] | None = None
    """
    A list of trusted IP addresses for connecting to this Managed Database (in CIDR notation).
    """
    user: str | None = None
    """
    The default user configured on creation. Published as a connection secret.
    """
    vpcId: str | None = None
    """
    The id of the VPC Network attached to the Managed Database.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    """
    AtProvider holds the observed values from the Vultr API.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Database(BaseModel):
    apiVersion: Literal['vultr.m.crossplane.io/v1alpha1'] | None = (
        'vultr.m.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Database'] | None = 'Database'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    DatabaseSpec defines the desired state of Database.
    """
    status: Status | None = None
    """
    DatabaseStatus defines the observed state of Database.
    """


class DatabaseList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Database]
    """
    List of databases. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """