# generated by datamodel-codegen:
#   filename:  workdir/infrastructure_modelplane_ai_v1alpha1_vultrcluster.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, conint, constr

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class Credentials(BaseModel):
    name: constr(min_length=1, max_length=253) | None = 'default'
    type: Literal['ProviderConfig', 'ClusterProviderConfig'] | None = (
        'ClusterProviderConfig'
    )


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Gpu(BaseModel):
    acceleratorType: constr(min_length=1, max_length=63)
    """
    GPU accelerator type (e.g. nvidia-l40s, nvidia-a100). Used to label GPU nodes; the actual GPU and count are determined by the plan.
    """


class NodePool(BaseModel):
    gpu: Gpu | None = None
    """
    GPU configuration. Required when role is GPU.
    """
    maxNodeCount: conint(ge=1, le=1000) | None = None
    """
    Maximum number of nodes for autoscaling. When set the node pool autoscales between minNodeCount (or nodeCount) and this; VKE autoscaling is server-side, no in-cluster autoscaler is installed. Omit for fixed-size pools.
    """
    minNodeCount: conint(ge=1, le=1000) | None = None
    """
    Minimum number of nodes for autoscaling. Defaults to nodeCount when maxNodeCount is set. Requires maxNodeCount.
    """
    name: constr(min_length=1, max_length=40)
    """
    Unique name for this node pool. Used as the pool's label in the VKE cluster.
    """
    nodeCount: conint(ge=1, le=1000) | None = 1
    """
    Number of nodes. Fixed unless maxNodeCount enables autoscaling. VKE pools always run at least one node.
    """
    plan: constr(min_length=1, max_length=63)
    """
    Vultr plan ID for the pool's nodes (e.g. vcg-l40s-16c-180g-48vram, vc2-6c-16gb). This is the instance type used by other clouds; list plans with vultr-cli plans list.
    """
    role: Literal['System', 'GPU']
    """
    Determines what workloads this pool runs. System pools host controllers, gateways, and infrastructure. GPU pools host inference workloads and are tainted to exclude non-GPU pods.
    """


class Spec(BaseModel):
    credentials: Credentials | None = None
    """
    Vultr ProviderConfig or ClusterProviderConfig used to authenticate to the Vultr API. Defaults to the ClusterProviderConfig named default.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    kubernetesVersion: constr(min_length=1, max_length=16) | None = 'v1.36.2+1'
    """
    VKE cluster Kubernetes version. VKE requires an exact version string including the build suffix; list current versions with vultr-cli kubernetes versions. Defaults to a version where Dynamic Resource Allocation (how GPUs bind to pods) is generally available.
    """
    nodePools: list[NodePool] = Field(..., max_length=8, min_length=1)
    """
    Node pools for the cluster. At least one System pool is required for controllers and infrastructure workloads.
    """
    region: constr(min_length=1, max_length=32)
    """
    Vultr region for the cluster (e.g. ewr, fra). GPU plans and Vultr File System availability vary by region.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Secret(BaseModel):
    key: constr(max_length=253)
    """
    Key within the Secret that holds the credential data.
    """
    name: constr(max_length=253)
    """
    Name of the Secret.
    """
    type: Literal['Kubeconfig'] = 'Kubeconfig'
    """
    The type of credential this secret contains. Kubeconfig contains a kubeconfig file with the cluster endpoint, CA certificate, and static client certificates.
    """


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    secrets: list[Secret] | None = None
    """
    Secrets produced by this cluster. Consumers use these to authenticate to the cluster. All secrets are in the same namespace as this VultrCluster.
    """


class VultrCluster(BaseModel):
    apiVersion: Literal['infrastructure.modelplane.ai/v1alpha1'] | None = (
        'infrastructure.modelplane.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['VultrCluster'] | None = 'VultrCluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    VultrClusterSpec defines the desired state of VultrCluster.
    """
    status: Status | None = None
    """
    VultrClusterStatus defines the observed state of VultrCluster.
    """


class VultrClusterList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[VultrCluster]
    """
    List of vultrclusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """