# generated by datamodel-codegen:
#   filename:  workdir/vultr_crossplane_io_v1alpha1_loadbalancer.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ....k8s.apimachinery.pkg.apis.meta import v1


class AutoSsl(BaseModel):
    domain: str | None = None
    """
    Full domain including domain zone and subdomain. Response-side only.
    """
    domainSub: str | None = None
    """
    (optional) Subdomain to append to the domain zone. Request-side only.
    """
    domainZone: str | None = None
    """
    The domain zone. (example.com)
    """


class FirewallRule(BaseModel):
    id: str | None = None
    """
    A unique ID for the firewall rule. Response-side only.
    """
    ipType: str | None = None
    """
    The type of IP rule. v4 or v6.
    """
    port: int | None = None
    """
    Port for this rule.
    """
    source: str | None = None
    """
    If the source string is given a value of "cloudflare" then cloudflare IPs will be supplied. Otherwise enter an IP address with subnet size that you wish to permit through the firewall.
    """


class ForwardingRule(BaseModel):
    backendPort: int | None = None
    """
    The port number destination on the backend server.
    """
    backendProtocol: str | None = None
    """
    The protocol destination on the backend server (HTTP, HTTPS, TCP, UDP).
    """
    frontendPort: int | None = None
    """
    The port number on the Load Balancer to forward to the backend.
    """
    frontendProtocol: str | None = None
    """
    The protocol on the Load Balancer to forward to the backend (HTTP, HTTPS, TCP, UDP).
    """


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class VpcIDRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpcIDSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class GlobalRegion(BaseModel):
    regionId: str | None = None
    """
    A Region id to deploy child Load Balancers to.
    """
    vpcIDRef: VpcIDRef | None = None
    """
    A Reference to a named object.
    """
    vpcIDSelector: VpcIDSelector | None = None
    """
    A Selector selects an object.
    """
    vpcId: str | None = None
    """
    ID of the VPC attached to the child Load Balancer in this region. Empty when no VPC is attached.
    """


class HealthCheck(BaseModel):
    checkInterval: int | None = None
    """
    Interval between health checks.
    """
    healthyThreshold: int | None = None
    """
    Number of times a check must succeed before returning to healthy status.
    """
    path: str | None = None
    """
    HTTP Path to check. Only applies if protocol is HTTP or HTTPS.
    """
    port: int | None = None
    """
    The port to use for health checks.
    """
    protocol: str | None = None
    """
    The protocol to use for health checks. HTTPS, HTTP, or TCP.
    """
    responseTimeout: int | None = None
    """
    Timeout before health check fails.
    """
    unhealthyThreshold: int | None = None
    """
    Number of times a check must fail before becoming unhealthy.
    """


class InstancesRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class InstancesSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class Ssl(BaseModel):
    certificate: str | None = None
    """
    The SSL certificate.
    """
    certificateB64: str | None = None
    """
    The SSL certificate base64 encoded. (Base64 encoded values should not be used alongside non-base64 encoded values.)
    """
    chain: str | None = None
    """
    The certificate chain.
    """
    chainB64: str | None = None
    """
    The certificate chain base64 encoded. (Base64 encoded values should not be used alongside non-base64 encoded values.)
    """
    privateKey: str | None = None
    """
    The private key.
    """
    privateKeyB64: str | None = None
    """
    The private key base64 encoded. (Base64 encoded values should not be used alongside non-base64 encoded values.)
    """


class StickySession(BaseModel):
    cookieName: str | None = None
    """
    The cookie name to make sticky.
    """


class VpcRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpcSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    autoSsl: AutoSsl | None = None
    """
    The Auto SSL configuration. Must be using Vultr DNS for Auto SSL.
    """
    balancingAlgorithm: str | None = None
    """
    The balancing algorithm. roundrobin (default) or leastconn.
    """
    firewallRules: list[FirewallRule] | None = None
    """
    An array of firewall rule objects.
    """
    forwardingRules: list[ForwardingRule] | None = None
    """
    An array of forwarding rule objects.
    """
    globalRegions: list[GlobalRegion] | None = None
    """
    Array of regions that child Load Balancers are deployed to, including the VPC attached in each region.
    """
    healthCheck: HealthCheck | None = None
    """
    The health check object configuration.
    """
    http2: bool | None = None
    """
    Indicates if this Load Balancer has HTTP2 enabled. You must have an HTTPS forwarding rule combo (HTTPS -> HTTPS) to enable this option.
    """
    http3: bool | None = None
    """
    Indicates if this Load Balancer has HTTP3/QUIC enabled. You must have HTTP2 enabled.
    """
    instances: list[str] | None = None
    """
    Array of Instance ids attached to this Load Balancer.
    """
    instancesRefs: list[InstancesRef] | None = None
    instancesSelector: InstancesSelector | None = None
    """
    A Selector selects an object.
    """
    label: str | None = None
    """
    The user-supplied label for this Load Balancer.
    """
    nodes: int | None = None
    """
    The number of nodes to add to the load balancer (1-99), must be an odd number. This defaults to 1.
    """
    privateNetwork: str | None = None
    """
    Deprecated: use vpc instead. ID of the private network you wish to use. If privateNetwork is omitted it will default to the public network.
    """
    proxyProtocol: bool | None = None
    """
    If true, you must configure backend nodes to accept Proxy protocol. Defaults to false.
    """
    region: str | None = None
    """
    The Region id where the Load Balancer is located.
    """
    ssl: Ssl | None = None
    """
    An SSL certificate to install on the Load Balancer.
    """
    sslRedirect: bool | None = None
    """
    If true, this will redirect all HTTP traffic to HTTPS. You must have an HTTPS rule and SSL certificate installed on the load balancer to enable this option.
    """
    stickySession: StickySession | None = None
    """
    Enables sticky sessions for your load balancer when a cookie name is provided.
    """
    timeout: int | None = None
    """
    The maximum time allowed for the connection to remain inactive before timing out in seconds. This defaults to 600.
    """
    vpc: str | None = None
    """
    ID of the VPC you wish to use. If a VPC ID is omitted it will default to the public network.
    """
    vpcRef: VpcRef | None = None
    """
    A Reference to a named object.
    """
    vpcSelector: VpcSelector | None = None
    """
    A Selector selects an object.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    """
    ForProvider holds the user-supplied parameters for this Loadbalancer.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class ForwardRule(BaseModel):
    backendPort: int | None = None
    """
    The port number destination on the backend server.
    """
    backendPortocol: str | None = None
    """
    The protocol destination on the backend server (HTTP, HTTPS, TCP, UDP). NOTE: `backendPortocol` preserves an upstream Vultr API spelling defect (the response schema key is literally `backend_portocol`, missing an 'r') — kept verbatim for wire fidelity.
    """
    frontendPort: int | None = None
    """
    The port number on the Load Balancer to forward to the backend.
    """
    frontendProtocol: str | None = None
    """
    The protocol on the Load Balancer to forward to the backend (HTTP, HTTPS, TCP, UDP).
    """
    id: str | None = None
    """
    A unique ID for the forwarding rule.
    """


class StickySessions(BaseModel):
    cookieName: str | None = None
    """
    The cookie name to make sticky.
    """


class GenericInfo(BaseModel):
    balancingAlgorithm: str | None = None
    """
    The balancing algorithm. roundrobin (default) or leastconn.
    """
    privateNetwork: str | None = None
    """
    Deprecated: use vpc instead. ID of the private network in use.
    """
    proxyProtocol: bool | None = None
    """
    Whether backend nodes must accept Proxy protocol.
    """
    sslRedirect: bool | None = None
    """
    Whether HTTP traffic is redirected to HTTPS.
    """
    stickySessions: StickySessions | None = None
    """
    Sticky session cookie configuration.
    """
    timeout: int | None = None
    """
    The maximum time allowed for the connection to remain inactive before timing out in seconds.
    """
    vpc: str | None = None
    """
    ID of the VPC in use.
    """


class NodeIps(BaseModel):
    private: list[str] | None = None
    """
    Internal IP addresses assigned to the nodes within the VPC when a load balancer is configured in the VPC.
    """
    v4: list[str] | None = None
    """
    IPv4 addresses of the load balancer nodes.
    """
    v6: list[str] | None = None
    """
    IPv6 addresses of the load balancer nodes.
    """


class AtProvider(BaseModel):
    autoSsl: AutoSsl | None = None
    """
    The Auto SSL configuration. Must be using Vultr DNS for Auto SSL.
    """
    balancingAlgorithm: str | None = None
    """
    The balancing algorithm. roundrobin (default) or leastconn.
    """
    cname: str | None = None
    """
    The Canonical Name (CNAME) record value.
    """
    dateCreated: str | None = None
    """
    Date this Load Balancer was created.
    """
    firewallRules: list[FirewallRule] | None = None
    """
    An array of firewall rule objects.
    """
    forwardRules: list[ForwardRule] | None = None
    """
    An array of forwarding rule objects, as returned by GET. Distinct from the request-side forwardingRules field (the Vultr API uses different field names and item shapes for the request vs. response representation of forwarding rules).
    """
    forwardingRules: list[ForwardingRule] | None = None
    """
    An array of forwarding rule objects.
    """
    genericInfo: GenericInfo | None = None
    """
    An object containing additional options.
    """
    globalChildrenIds: list[str] | None = None
    """
    If this load balancer is the parent of a global load balancer, this field will display an array of children load balancer ids.
    """
    globalCname: str | None = None
    """
    The Canonical Name (CNAME) record value.
    """
    globalParentId: str | None = None
    """
    If this load balancer is a child of a global load balancer, this field will display the ID of the parent load balancer.
    """
    globalRegions: list[GlobalRegion] | None = None
    """
    Array of regions that child Load Balancers are deployed to, including the VPC attached in each region.
    """
    hasSsl: bool | None = None
    """
    Indicates if this Load Balancer has an SSL certificate installed.
    """
    healthCheck: HealthCheck | None = None
    """
    The health check object configuration.
    """
    http2: bool | None = None
    """
    Indicates if this Load Balancer has HTTP2 enabled. You must have an HTTPS forwarding rule combo (HTTPS -> HTTPS) to enable this option.
    """
    http3: bool | None = None
    """
    Indicates if this Load Balancer has HTTP3/QUIC enabled. You must have HTTP2 enabled.
    """
    id: str | None = None
    """
    A unique ID for the Load Balancer.
    """
    instances: list[str] | None = None
    """
    Array of Instance ids attached to this Load Balancer.
    """
    ipv4: str | None = None
    """
    The IPv4 address of this Load Balancer.
    """
    ipv6: str | None = None
    """
    The IPv6 address of this Load Balancer.
    """
    label: str | None = None
    """
    The user-supplied label for this Load Balancer.
    """
    nodeIps: NodeIps | None = None
    """
    Public IP addresses of the load balancer nodes.
    """
    nodes: int | None = None
    """
    The number of nodes to add to the load balancer (1-99), must be an odd number. This defaults to 1.
    """
    pendingCharges: float | None = None
    """
    Pending charges for the current billing period.
    """
    privateNetwork: str | None = None
    """
    Deprecated: use vpc instead. ID of the private network you wish to use. If privateNetwork is omitted it will default to the public network.
    """
    proxyProtocol: bool | None = None
    """
    If true, you must configure backend nodes to accept Proxy protocol. Defaults to false.
    """
    region: str | None = None
    """
    The Region id where the Load Balancer is located.
    """
    ssl: Ssl | None = None
    """
    An SSL certificate to install on the Load Balancer.
    """
    sslCertB64: str | None = None
    """
    Base64 encoded ssl certificate, private key, and chain.
    """
    sslRedirect: bool | None = None
    """
    If true, this will redirect all HTTP traffic to HTTPS. You must have an HTTPS rule and SSL certificate installed on the load balancer to enable this option.
    """
    status: str | None = None
    """
    The current status.
    """
    stickySession: StickySession | None = None
    """
    Enables sticky sessions for your load balancer when a cookie name is provided.
    """
    timeout: int | None = None
    """
    The maximum time allowed for the connection to remain inactive before timing out in seconds. This defaults to 600.
    """
    vpc: str | None = None
    """
    ID of the VPC you wish to use. If a VPC ID is omitted it will default to the public network.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    """
    AtProvider holds the observed values from the Vultr API.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Loadbalancer(BaseModel):
    apiVersion: Literal['vultr.crossplane.io/v1alpha1'] | None = (
        'vultr.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Loadbalancer'] | None = 'Loadbalancer'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    LoadbalancerSpec defines the desired state of Loadbalancer.
    """
    status: Status | None = None
    """
    LoadbalancerStatus defines the observed state of Loadbalancer.
    """


class LoadbalancerList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Loadbalancer]
    """
    List of loadbalancers. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """