# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_inferenceclass.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, conint, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None
    namespace: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Accelerator(BaseModel):
    count: conint(ge=1, le=16)
    type: constr(min_length=1, max_length=63)
    """
    GPU accelerator type (e.g. nvidia-a10g, nvidia-h100). Informational - reported on the consuming InferenceCluster's status.
    """


class Eks(BaseModel):
    accelerator: Accelerator
    diskSizeGb: conint(ge=10) | None = 100
    instanceType: constr(min_length=1)
    """
    EC2 instance type (e.g. g6.xlarge, p4d.24xlarge). The instance family determines the GPU model; the accelerator block below is informational.
    """


class AcceleratorModel(BaseModel):
    count: conint(ge=1, le=16)
    type: constr(min_length=1, max_length=63)
    """
    GPU accelerator type passed to GCP (e.g. nvidia-l4, nvidia-h100-80gb).
    """


class Gke(BaseModel):
    accelerator: AcceleratorModel
    diskSizeGb: conint(ge=10) | None = 100
    machineType: constr(min_length=1)


class Provisioning(BaseModel):
    eks: Eks | None = None
    gke: Gke | None = None
    provider: Literal['GKE', 'EKS']


class Gpu(BaseModel):
    count: conint(ge=1, le=16)
    """
    GPUs per node.
    """
    memory: constr(min_length=1, max_length=16)
    """
    Per-GPU VRAM (e.g. "24Gi", "80Gi").
    """


class Resources(BaseModel):
    gpu: Gpu


class Spec(BaseModel):
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    description: str | None = None
    """
    Human-readable description of the class.
    """
    provisioning: Provisioning | None = None
    """
    How to provision a node pool of this class. Omit for classes that describe BYO node pools that already exist.
    """
    resources: Resources
    """
    Hardware resources a node of this class exposes.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """


class InferenceClass(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['InferenceClass'] | None = 'InferenceClass'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    status: Status | None = None


class InferenceClassList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[InferenceClass]
    """
    List of inferenceclasses. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """