# generated by datamodel-codegen:
#   filename:  workdir/vultr_m_crossplane_io_v1alpha1_registry.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class ForProvider(BaseModel):
    name: str
    """
    The globally unique name to reference this registry.
    """
    plan: str
    """
    The key of the plan you'd like to select which dictates how much storage you're allocated and the monthly cost. Can get list of plans from /plan/list endpoint i.e. start_up.
    """
    public: bool
    """
    If true, this is a publically accessible registry allowing anyone to pull from it. If false, this registry is completely private.
    """
    region: str
    """
    The name of the region you'd like to deploy this Registry in. Can get list of regions from /registry/region/list endpoint i.e. sjc.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    """
    ForProvider holds the user-supplied parameters for this Registry.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class Region(BaseModel):
    addedAt: str | None = None
    """
    The date this Region was added.
    """
    baseUrl: str | None = None
    """
    The base URL of this region.
    """
    id: int | None = None
    """
    The Numeric ID of this region.
    """
    name: str | None = None
    """
    The unique name of this region, used to specify a region when creating a subscription.
    """
    public: bool | None = None
    """
    If true, this is a publically accessible region allowing any customer to create new subscriptions on this region. If false, this region is not generally available yet.
    """
    updatedAt: str | None = None
    """
    The date this Region was last updated.
    """
    urn: str | None = None
    """
    The base URN (the URL without the scheme [i.e. http:// or https://]) of this region.
    """


class Billing(BaseModel):
    monthlyPrice: float | None = None
    """
    Monthly Price.
    """
    pendingCharges: float | None = None
    """
    The current charges for this subscription.
    """


class Subscription(BaseModel):
    billing: Billing | None = None
    """
    Billing information for this subscription.
    """
    plan: str | None = None
    """
    The plan used by this container registry. One of the plans returned by the List Registry Plans endpoint.
    """


class Metadata(BaseModel):
    region: Region | None = None
    """
    The region where this registry subscription lives.
    """
    subscription: Subscription | None = None
    """
    Subscription information for this registry.
    """


class RootUser(BaseModel):
    addedAt: str | None = None
    """
    The date this User was added.
    """
    id: int | None = None
    """
    The Numeric ID of this user.
    """
    password: str | None = None
    """
    The password this user will use to authenticate.
    """
    root: bool | None = None
    """
    If true, this is a root user/registry owner meaning it cannot be deleted or renamed. If false, this is an additional user added to this registry that can be modified.
    """
    updatedAt: str | None = None
    """
    The date this User was last updated.
    """
    username: str | None = None
    """
    The globally unique name of this user.
    """


class Allowed(BaseModel):
    bytes: float | None = None
    """
    Storage in Bytes.
    """
    gb: float | None = None
    """
    Storage in Gigabytes.
    """
    mb: float | None = None
    """
    Storage in Megabytes.
    """
    tb: float | None = None
    """
    Storage in Terabytes.
    """
    updatedAt: str | None = None
    """
    The date at which the storage information was last updated.
    """


class Used(BaseModel):
    bytes: float | None = None
    """
    Storage in Bytes.
    """
    gb: float | None = None
    """
    Storage in Gigabytes.
    """
    mb: float | None = None
    """
    Storage in Megabytes.
    """
    tb: float | None = None
    """
    Storage in Terabytes.
    """
    updatedAt: str | None = None
    """
    The date at which the storage information was last updated.
    """


class Storage(BaseModel):
    allowed: Allowed | None = None
    """
    The storage allowed for this registry subscription.
    """
    used: Used | None = None
    """
    The storage used by this registry subscription.
    """


class AtProvider(BaseModel):
    dateCreated: str | None = None
    """
    The date this Registry Subscription was created.
    """
    id: str | None = None
    """
    The UUID to reference this registry.
    """
    metadata: Metadata | None = None
    """
    The metadata containing subscription information such as the region where this registry lives and monthly price and pending charges.
    """
    name: str | None = None
    """
    The globally unique name to reference this registry.
    """
    plan: str | None = None
    """
    The key of the plan you'd like to select which dictates how much storage you're allocated and the monthly cost. Can get list of plans from /plan/list endpoint i.e. start_up.
    """
    public: bool | None = None
    """
    If true, this is a publically accessible registry allowing anyone to pull from it. If false, this registry is completely private.
    """
    region: str | None = None
    """
    The name of the region you'd like to deploy this Registry in. Can get list of regions from /registry/region/list endpoint i.e. sjc.
    """
    rootUser: RootUser | None = None
    """
    Container Registry User Entity.
    """
    storage: Storage | None = None
    """
    The allowed and used storage for this registry subscription.
    """
    urn: str | None = None
    """
    The base URN (the URL without the scheme [i.e. http:// or https://]) of this registry.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    """
    AtProvider holds the observed values from the Vultr API.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Registry(BaseModel):
    apiVersion: Literal['vultr.m.crossplane.io/v1alpha1'] | None = (
        'vultr.m.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Registry'] | None = 'Registry'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    RegistrySpec defines the desired state of Registry.
    """
    status: Status | None = None
    """
    RegistryStatus defines the observed state of Registry.
    """


class RegistryList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Registry]
    """
    List of registries. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """