# generated by datamodel-codegen:
#   filename:  workdir/vultr_m_crossplane_io_v1alpha1_instance.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class AttachVpcRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class AttachVpcSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class BlockIDRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class BlockIDSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class BlockDevice(BaseModel):
    blockIDRef: BlockIDRef | None = None
    """
    A NamespacedReference to a named object.
    """
    blockIDSelector: BlockIDSelector | None = None
    """
    NamespacedSelector selects a namespaced object.
    """
    blockId: str | None = None
    """
    The id of an existing Block Storage volume to attach, or "local" for local storage.
    """
    bootable: bool | None = None
    """
    Whether this block device should be used as the boot disk.
    """
    diskSize: int | None = None
    """
    The size in GB of a new Block Storage volume to create and attach.
    """
    label: str | None = None
    """
    The label for a new Block Storage volume to create and attach.
    """


class FirewallGroupIDRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class FirewallGroupIDSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ReservedIpv4Ref(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ReservedIpv4Selector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ScriptIDRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ScriptIDSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class SnapshotIDRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SnapshotIDSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class SshkeyIDRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SshkeyIDSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    activationEmail: bool | None = None
    """
    Notify by email after deployment.
    """
    appId: int | None = None
    """
    The Application id used by this instance.
    """
    appVariables: dict[str, str] | None = None
    """
    The app variable inputs for configuring the marketplace app (name/value pairs).
    """
    attachPrivateNetwork: list[str] | None = None
    """
    Deprecated: use attachVpc instead. An array of Private Network ids to attach to this Instance. Takes precedence over enablePrivateNetwork.
    """
    attachVpc: list[str] | None = None
    """
    An array of VPC ids to attach to this Instance. Takes precedence over enableVpc.
    """
    attachVpc2: list[str] | None = None
    """
    Deprecated: use attachVpc instead. An array of VPC 2.0 ids to attach to this Instance. Takes precedence over enableVpc2.
    """
    attachVpcRefs: list[AttachVpcRef] | None = None
    attachVpcSelector: AttachVpcSelector | None = None
    """
    NamespacedSelector selects a namespaced object.
    """
    backups: Literal['enabled', 'disabled'] | None = None
    """
    Enable automatic backups for the instance (does not work for VX1 block storage).
    """
    blockDevices: list[BlockDevice] | None = None
    """
    Available for VX1 instances: define block devices, create bootable block devices, or use local storage (if the plan has local storage) as a scratch disk.
    """
    ddosProtection: bool | None = None
    """
    Enable DDoS protection (there is an additional charge for this).
    """
    detachPrivateNetwork: list[str] | None = None
    """
    Deprecated: use detachVpc instead. An array of Private Network ids to detach from this Instance. Request-only — never returned in a GET response.
    """
    detachVpc: list[str] | None = None
    """
    An array of VPC ids to detach from this Instance. Request-only — never returned in a GET response.
    """
    detachVpc2: list[str] | None = None
    """
    Deprecated: use detachVpc instead. An array of VPC 2.0 ids to detach from this Instance. Request-only — never returned in a GET response.
    """
    disablePublicIpv4: bool | None = None
    """
    Don't set up a public IPv4 address when IPv6 is enabled. Has no effect unless enableIpv6 is also true.
    """
    enableIpv6: bool | None = None
    """
    Enable IPv6.
    """
    enablePrivateNetwork: bool | None = None
    """
    Deprecated: use enableVpc instead. If true, private networking support will be added to the new server.
    """
    enableVpc: bool | None = None
    """
    If true, VPC support will be added to the new server.
    """
    enableVpc2: bool | None = None
    """
    Deprecated: use enableVpc instead. If true, VPC 2.0 support will be added to the new server.
    """
    firewallGroupIDRef: FirewallGroupIDRef | None = None
    """
    A NamespacedReference to a named object.
    """
    firewallGroupIDSelector: FirewallGroupIDSelector | None = None
    """
    NamespacedSelector selects a namespaced object.
    """
    firewallGroupId: str | None = None
    """
    The Firewall Group id linked to this Instance.
    """
    hostname: str | None = None
    """
    The hostname for this instance.
    """
    imageId: str | None = None
    """
    The Application image_id used by this instance.
    """
    ipxeChainUrl: str | None = None
    """
    The URL location of the iPXE chainloader.
    """
    isoId: str | None = None
    """
    The ISO id to use when deploying this instance.
    """
    label: str | None = None
    """
    The user-supplied label for this instance.
    """
    osId: int | None = None
    """
    The Operating System id used by this instance.
    """
    plan: str
    """
    A unique ID for the Plan.
    """
    region: str
    """
    The Region id where the Instance is located.
    """
    reservedIpv4: str | None = None
    """
    ID of the floating IP to use as the main IP of this server.
    """
    reservedIpv4Ref: ReservedIpv4Ref | None = None
    """
    A NamespacedReference to a named object.
    """
    reservedIpv4Selector: ReservedIpv4Selector | None = None
    """
    NamespacedSelector selects a namespaced object.
    """
    scriptIDRef: ScriptIDRef | None = None
    """
    A NamespacedReference to a named object.
    """
    scriptIDSelector: ScriptIDSelector | None = None
    """
    NamespacedSelector selects a namespaced object.
    """
    scriptId: str | None = None
    """
    The Startup Script id to use when deploying this instance.
    """
    snapshotIDRef: SnapshotIDRef | None = None
    """
    A NamespacedReference to a named object.
    """
    snapshotIDSelector: SnapshotIDSelector | None = None
    """
    NamespacedSelector selects a namespaced object.
    """
    snapshotId: str | None = None
    """
    The Snapshot id used by this instance.
    """
    sshkeyIDRefs: list[SshkeyIDRef] | None = None
    sshkeyIDSelector: SshkeyIDSelector | None = None
    """
    NamespacedSelector selects a namespaced object.
    """
    sshkeyId: list[str] | None = None
    """
    The SSH Key id(s) to install on this instance.
    """
    tag: str | None = None
    """
    Deprecated: use tags instead. The user-supplied tag for this instance.
    """
    tags: list[str] | None = None
    """
    Tags to apply to the instance.
    """
    userData: str | None = None
    """
    The user-supplied, base64 encoded user data to attach to this instance.
    """
    userScheme: Literal['root', 'limited'] | None = None
    """
    The user scheme used for logging into this instance (Linux-only).
    """
    vpcOnly: bool | None = None
    """
    If true, this instance will not receive a public IP and instead gets internet access through a NAT Gateway on the attached VPC.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    """
    ForProvider holds the user-supplied parameters for this Instance.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class V6Network(BaseModel):
    mainIp: str | None = None
    """
    The main IPv6 network address.
    """
    network: str | None = None
    """
    The IPv6 subnet.
    """
    networkSize: int | None = None
    """
    The IPv6 network size in bits.
    """


class Vpc(BaseModel):
    id: str | None = None
    """
    The ID of the VPC Network.
    """
    subnet: str | None = None
    """
    The IP subnet used for the instance on the VPC Network.
    """
    version: int | None = None
    """
    Deprecated. The version of VPC (1 or 2).
    """


class AtProvider(BaseModel):
    activationEmail: bool | None = None
    """
    Notify by email after deployment.
    """
    allowedBandwidth: int | None = None
    """
    Monthly bandwidth quota in GB.
    """
    appId: int | None = None
    """
    The Application id used by this instance.
    """
    appVariables: dict[str, str] | None = None
    """
    The app variable inputs for configuring the marketplace app (name/value pairs).
    """
    attachPrivateNetwork: list[str] | None = None
    """
    Deprecated: use attachVpc instead. An array of Private Network ids to attach to this Instance. Takes precedence over enablePrivateNetwork.
    """
    attachVpc: list[str] | None = None
    """
    An array of VPC ids to attach to this Instance. Takes precedence over enableVpc.
    """
    attachVpc2: list[str] | None = None
    """
    Deprecated: use attachVpc instead. An array of VPC 2.0 ids to attach to this Instance. Takes precedence over enableVpc2.
    """
    backups: str | None = None
    """
    Enable automatic backups for the instance (does not work for VX1 block storage).
    """
    blockDevices: list[BlockDevice] | None = None
    """
    Available for VX1 instances: define block devices, create bootable block devices, or use local storage (if the plan has local storage) as a scratch disk.
    """
    dateCreated: str | None = None
    """
    The date this instance was created.
    """
    ddosProtection: bool | None = None
    """
    Enable DDoS protection (there is an additional charge for this).
    """
    defaultPassword: str | None = None
    """
    The default password assigned at deployment. Only available for ten minutes after deployment. Published as a connection secret.
    """
    detachPrivateNetwork: list[str] | None = None
    """
    Deprecated: use detachVpc instead. An array of Private Network ids to detach from this Instance. Request-only — never returned in a GET response.
    """
    detachVpc: list[str] | None = None
    """
    An array of VPC ids to detach from this Instance. Request-only — never returned in a GET response.
    """
    detachVpc2: list[str] | None = None
    """
    Deprecated: use detachVpc instead. An array of VPC 2.0 ids to detach from this Instance. Request-only — never returned in a GET response.
    """
    disablePublicIpv4: bool | None = None
    """
    Don't set up a public IPv4 address when IPv6 is enabled. Has no effect unless enableIpv6 is also true.
    """
    disk: int | None = None
    """
    The size of the disk in GB.
    """
    enableIpv6: bool | None = None
    """
    Enable IPv6.
    """
    enablePrivateNetwork: bool | None = None
    """
    Deprecated: use enableVpc instead. If true, private networking support will be added to the new server.
    """
    enableVpc: bool | None = None
    """
    If true, VPC support will be added to the new server.
    """
    enableVpc2: bool | None = None
    """
    Deprecated: use enableVpc instead. If true, VPC 2.0 support will be added to the new server.
    """
    features: list[str] | None = None
    """
    Feature flags active on this instance, e.g. "auto_backups", "ipv6", "ddos_protection".
    """
    firewallGroupId: str | None = None
    """
    The Firewall Group id linked to this Instance.
    """
    gatewayV4: str | None = None
    """
    The gateway IP address.
    """
    hostname: str | None = None
    """
    The hostname for this instance.
    """
    id: str | None = None
    """
    A unique ID for the VPS Instance.
    """
    imageId: str | None = None
    """
    The Application image_id used by this instance.
    """
    internalIp: str | None = None
    """
    The internal IP used by this instance, if set. Only relevant when a VPC is attached.
    """
    ipxeChainUrl: str | None = None
    """
    The URL location of the iPXE chainloader.
    """
    isoId: str | None = None
    """
    The ISO id to use when deploying this instance.
    """
    kvm: str | None = None
    """
    HTTPS link to the Vultr noVNC Web Console.
    """
    label: str | None = None
    """
    The user-supplied label for this instance.
    """
    mainIp: str | None = None
    """
    The main IPv4 address.
    """
    netmaskV4: str | None = None
    """
    The IPv4 netmask in dot-decimal notation.
    """
    os: str | None = None
    """
    The Operating System name.
    """
    osId: int | None = None
    """
    The Operating System id used by this instance.
    """
    plan: str | None = None
    """
    A unique ID for the Plan.
    """
    powerStatus: str | None = None
    """
    The power-on status.
    """
    ram: int | None = None
    """
    The amount of RAM in MB.
    """
    region: str | None = None
    """
    The Region id where the Instance is located.
    """
    reservedIpv4: str | None = None
    """
    ID of the floating IP to use as the main IP of this server.
    """
    scriptId: str | None = None
    """
    The Startup Script id to use when deploying this instance.
    """
    serverStatus: str | None = None
    """
    The server health status.
    """
    snapshotId: str | None = None
    """
    The Snapshot id used by this instance.
    """
    sshkeyId: list[str] | None = None
    """
    The SSH Key id(s) to install on this instance.
    """
    status: str | None = None
    """
    The current status.
    """
    tag: str | None = None
    """
    Deprecated: use tags instead. The user-supplied tag for this instance.
    """
    tags: list[str] | None = None
    """
    Tags to apply to the instance.
    """
    userData: str | None = None
    """
    The user-supplied, base64 encoded user data to attach to this instance.
    """
    userScheme: str | None = None
    """
    The user scheme used for logging into this instance (Linux-only).
    """
    v6Networks: list[V6Network] | None = None
    """
    An array of IPv6 objects.
    """
    vcpuCount: int | None = None
    """
    Number of vCPUs.
    """
    vpcOnly: bool | None = None
    """
    If true, this instance will not receive a public IP and instead gets internet access through a NAT Gateway on the attached VPC.
    """
    vpcs: list[Vpc] | None = None
    """
    List of VPC Networks to which the instance is attached.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    """
    AtProvider holds the observed values from the Vultr API.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Instance(BaseModel):
    apiVersion: Literal['vultr.m.crossplane.io/v1alpha1'] | None = (
        'vultr.m.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Instance'] | None = 'Instance'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    InstanceSpec defines the desired state of Instance.
    """
    status: Status | None = None
    """
    InstanceStatus defines the observed state of Instance.
    """


class InstanceList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Instance]
    """
    List of instances. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """