# generated by datamodel-codegen:
#   filename:  workdir/vultr_crossplane_io_v1alpha1_natgateway.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class VpcIDRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpcIDSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    label: str | None = None
    """
    Label for the NAT Gateway. Defaults to "nat-gateway-{vpc-id}" if omitted. Mutable via PUT.
    """
    tag: str | None = None
    """
    User-supplied tag for the NAT Gateway. Defaults to an empty string if omitted. Mutable via PUT.
    """
    vpcIDRef: VpcIDRef | None = None
    """
    A Reference to a named object.
    """
    vpcIDSelector: VpcIDSelector | None = None
    """
    A Selector selects an object.
    """
    vpcId: str | None = None
    """
    The parent VPC's id. Populates the {vpc-id} path parameter and is echoed back in the nat_gateway response body. Only one NAT Gateway may exist per VPC.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    """
    ForProvider holds the user-supplied parameters for this NatGateway.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class Billing(BaseModel):
    charges: float | None = None
    """
    Current billing charges.
    """
    monthly: float | None = None
    """
    Monthly billing amount.
    """


class AtProvider(BaseModel):
    billing: Billing | None = None
    """
    Current billing state for the NAT Gateway subscription.
    """
    dateCreated: str | None = None
    """
    Date the NAT Gateway was created, formatted as "YYYY-MM-DD HH:MM:SS" (not RFC3339).
    """
    id: str | None = None
    """
    Server-assigned unique id for the NAT Gateway.
    """
    label: str | None = None
    """
    Label for the NAT Gateway. Defaults to "nat-gateway-{vpc-id}" if omitted. Mutable via PUT.
    """
    privateIps: list[str] | None = None
    """
    Server-assigned VPC-side private IP addresses for the NAT Gateway.
    """
    publicIps: list[str] | None = None
    """
    Server-assigned public IPv4 addresses for the NAT Gateway.
    """
    publicIpsV6: list[str] | None = None
    """
    Server-assigned public IPv6 addresses for the NAT Gateway.
    """
    status: str | None = None
    """
    Lifecycle status of the NAT Gateway: "pending" while provisioning (roughly 2.5 minutes), "active" once ready.
    """
    tag: str | None = None
    """
    User-supplied tag for the NAT Gateway. Defaults to an empty string if omitted. Mutable via PUT.
    """
    vpcId: str | None = None
    """
    The parent VPC's id. Populates the {vpc-id} path parameter and is echoed back in the nat_gateway response body. Only one NAT Gateway may exist per VPC.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    """
    AtProvider holds the observed values from the Vultr API.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class NatGateway(BaseModel):
    apiVersion: Literal['vultr.crossplane.io/v1alpha1'] | None = (
        'vultr.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['NatGateway'] | None = 'NatGateway'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    NatGatewaySpec defines the desired state of NatGateway.
    """
    status: Status | None = None
    """
    NatGatewayStatus defines the observed state of NatGateway.
    """


class NatGatewayList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[NatGateway]
    """
    List of natgateways. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """